# Generated by Django 5.1.3 on 2025-01-09 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ArticuloApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ped', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido_ped', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('correo_ped', models.CharField(max_length=100, verbose_name='Email')),
                ('tele_ped', models.CharField(max_length=100, verbose_name='Telefono')),
                ('dir_ped', models.CharField(max_length=100, verbose_name='Direccion')),
                ('ciudad_ped', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('estado_ped', models.CharField(max_length=100, verbose_name='Estado')),
                ('zip_ped', models.CharField(max_length=100, verbose_name='Zip')),
                ('creado_ped', models.DateTimeField(auto_now_add=True)),
                ('usr_ped', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'Pedidos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_Producto', models.IntegerField()),
                ('cant_Producto', models.IntegerField()),
                ('Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArticuloApp.producto')),
                ('Ped', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PedidosApp.pedidos')),
            ],
            options={
                'verbose_name': 'DetallePedidos',
                'verbose_name_plural': 'Detalle Pedidos',
                'db_table': 'Detalle Pedidos',
                'ordering': ['id'],
            },
        ),
    ]
